repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        always_run: true
        name: Execute the Ruff linter
        args: [ --fix ]
      - id: ruff-format
        always_run: true
        name: Execute the Ruff formatter (fix code)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: [
          --config-file=pyproject.toml,
        ]
        additional_dependencies: [
          "types-PyYAML",
          "types-requests",
          "types-python-dateutil",
        ]
