repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        always_run: true
        name: Execute the Ruff linter
        args: [ --fix ]
      - id: ruff-format
        always_run: true
        name: Execute the Ruff formatter (fix code)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        always_run: true
        args: [--strict, --ignore-missing-imports]
        additional_dependencies: [
          "types-PyYAML",
        ]
