repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        name: Execute the Ruff linter
        args: [ --fix ]
        types_or: [ python, pyi, jupyter ]
      - id: ruff-format
        name: Execute the Ruff formatter (fix code)
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: [
          --config-file=pyproject.toml,
        ]
        additional_dependencies: [
          "types-PyYAML",
          "types-requests",
          "types-python-dateutil",
        ]
